
# number of data elements to feed the model and once
timesteps: 50

dataset_folder: dataset

classes:
  - ippon:Ippon
  - matte:Matte
  - wazari:Wazari
  - scorechange:ScoreChange
  - shido:Shido
  - toketa:Toketa

ignored_classes:
  - ScoreChange
  - Toketa
  - Matte
